config/routes.rb
Rails.application.routes.draw do
 root to: "sessions#new"
 resources :users, :sessions, :events, :users_events, :comments

  patch 'users'				=> "users#update"

  delete 'sessions/:id'		=> "sessions#destroy"

  patch "events/:id"		=> "events#update"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :event

  validates :message, presence: true
  validates :message, length: { in: 2..500 }
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
  has_many :users_events
  has_many :comments

  validates :name,	:presence => true, length: { minimum: 6 }

  validates :city,	:presence => true

  validates :state,	:presence => true

  validates	:date,	:presence => true

  validates :time,	:presence => true 
  
  validate :event_future_date, on: :create

  def event_future_date
  	if date.present? && date < Date.today
  		errors.add(:date, "can't be in the past")
  	end
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :events
  has_many :users_events
  has_many :comments

  before_save { self.email = email.downcase }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :first_name, :presence => true

  validates :last_name, :presence => true

  validates :email, :presence => true, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
  
end

app/models/users_event.rb
class UsersEvent < ApplicationRecord
  belongs_to :user
  belongs_to :event

  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery prepend: true

  def current_user
  	User.find(session[:user_id]) if session[:user_id]
  end


  add_flash_types :danger, :info, :warning, :success
  helper_method :current_user
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
  	comment = Comment.create comment_params
  	if comment.save
  		redirect_to event_path(params[:comment][:event_id]),
  		flash: {success: "Comment Added"}
  	else
  		redirect_to event_path(params[:comment][:event_id]),
  		flash: { danger: "Error"}
  	end
  end

  def destroy
  end

 private

  def comment_params
  	params.require(:comment).permit(:message, :event_id, :user_id)
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @users = User.all
    @events = Event.all 
  end

  def new
  end

  def create
    @user = current_user
    @event = @user.events.new(event_params)
    if @event.save
      redirect_to events_path, flash: { success: "Your Event Has Been Added!"}
    else 
      redirect_to events_path, flash: { danger: @event.errors.full_messages }
    end
  end

  def edit
    @event = Event.find(params[:id])
  end

  def show
    @event = Event.find(params[:id])
    @comments = @event.comments
  end

  def update
    @event = Event.find(params[:id])
    if @event.update(event_params)
      redirect_to edit_event_path, flash: {success: "Successfully Updated!"}
    else 
      redirect_to edit_event_path, flash: {danger: @event.errors.full_messages}
    end
  end

  def destroy
    Event.find(params[:id]).destroy
    redirect_to events_path, flash: { warning: "You Have Deleted the Event"}
  end

  private

  def event_params
    params.require(:event).permit(:name, :date, :city, :state, :time)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	
  def new

  end

  def create
  	@user = User.find_by_email(login[:email])
  	if @user && @user.authenticate(login[:password])
  		session[:user_id] = @user.id 
  		redirect_to "/events"
  	else
  		redirect_to "/sessions/new", flash: { danger: "Invalid Credentials"}
  	end
  end

  def destroy
  	reset_session
  	redirect_to "/sessions/new"
  end

  private

  def login
  	params.require(:user).permit(:email, :password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end

  def index
  	@user = User.find(params[:id])
  end

  def create 
  	user = User.new user_params
  	if user.save
  		session[:user_id] = user.id
  		redirect_to "/events"
  	else
  		redirect_to "/sessions/new", flash: {danger: user.errors.full_messages.join(",")}
  	end
  end

  def edit
  	@user = current_user
  end

  def update
  	user = current_user
  	if user.update update_user_params
  		redirect_to edit_user_path(user), flash: {success: "Successfully Updated!"}
  	else
  		redirect_to edit_user_path(user), flash: {danger: user.errors.full_messages }
  	end
  end

  def destroy
  end

  private

  def update_user_params
  	params.require(:user).permit(:first_name, :last_name, :email, :city, :state )
  end

  def user_params
  	params.require(:user).permit(:first_name, :last_name, :email, :city, :state, :password, :password_confirmation)
  end
end

app/controllers/users_events_controller.rb
class UsersEventsController < ApplicationController
  def create
  @user_event = UsersEvent.create(event_id: params[:event_id], user: current_user )
    if @user_event.save 
        redirect_to events_path, flash: {success: "You have joined the event"}
    else
        redirect_to events_path, flash: {danger: @user_event.errors.full_messages }
    end
  end

  def destroy
    UsersEvent.find(params[:id]).destroy
    redirect_to events_path, flash: { warning: "You have left the event" }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/date_time_helper.rb
module DateTimeHelper
	def event_date(date)
	  	date.to_formatted_s(:long_ordinal)
	end

	def event_time(time)
		time.strftime("%I:%M %P")
	end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/location_helper.rb
module LocationHelper
	def states
		[
	    ['AK', 'AK'],
	    ['AL', 'AL'],
	    ['AR', 'AR'],
	    ['AZ', 'AZ'],
	    ['CA', 'CA'],
	    ['CO', 'CO'],
	    ['CT', 'CT'],
	    ['DC', 'DC'],
	    ['DE', 'DE'],
	    ['FL', 'FL'],
	    ['GA', 'GA'],
	    ['HI', 'HI'],
	    ['IA', 'IA'],
	    ['ID', 'ID'],
	    ['IL', 'IL'],
	    ['IN', 'IN'],
	    ['KS', 'KS'],
	    ['KY', 'KY'],
	    ['LA', 'LA'],
	    ['MA', 'MA'],
	    ['MD', 'MD'],
	    ['ME', 'ME'],
	    ['MI', 'MI'],
	    ['MN', 'MN'],
	    ['MO', 'MO'],
	    ['MS', 'MS'],
	    ['MT', 'MT'],
	    ['NC', 'NC'],
	    ['ND', 'ND'],
	    ['NE', 'NE'],
	    ['NH', 'NH'],
	    ['NJ', 'NJ'],
	    ['NM', 'NM'],
	    ['NV', 'NV'],
	    ['NY', 'NY'],
	    ['OH', 'OH'],
	    ['OK', 'OK'],
	    ['OR', 'OR'],
	    ['PA', 'PA'],
	    ['RI', 'RI'],
	    ['SC', 'SC'],
	    ['SD', 'SD'],
	    ['TN', 'TN'],
	    ['TX', 'TX'],
	    ['UT', 'UT'],
	    ['VA', 'VA'],
	    ['VT', 'VT'],
	    ['WA', 'WA'],
	    ['WI', 'WI'],
	    ['WV', 'WV'],
	    ['WY', 'WY']
	  ]
	end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_events_helper.rb
module UsersEventsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/edit.html.erb
<% provide(:page_title, 'Edit Event') %>
<%= render partial: "shared/navbar_edit", locals: { user: current_user } %>

<div class="row">
	<div class="col-md-3">
		<div class="edit_head">
			<h5>Edit Your Event</h5>
		</div>
	</div>
</div>

<div class="row justify-content-center">
	<div class="col-md-8">
		<form action="/events/<%= @event.id %>" method="post">
			<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
			<input type="hidden" name="_method" value="patch">

			<div class="form-group row">
				<label for="name" class="col-sm-4 col-form-label">Event Name</label>
				<div class="col-sm-6">
					<input type="text" class="form-control" id="name" name="event[name]" value="<%= @event.name %>">
				</div>
			</div>

			<div class="form-group row">
				<label for="date" class="col-sm-4 col-form-label">Date</label>
				<div class="col-sm-5">
					<input type="date" class="form-control" id="date" name="event[date]" value="<%= @event.date %>">
				</div>
			</div>

			<div class="form-group row">
				<label for="location" class="col-sm-4 col-form-label">Location</label>
				<div class="col-sm-4">
					<input type="text" id="city" name="event[city]" class="form-control" value="<%= @event.city %>">
				</div>
				<select name="event[state]" id="state" class="form-control col-sm-2">
					<% states.each do |key, state| %>
						<option value="<%= state %>" id="state" <% if state == @event.state %> selected="selected" <% end %> >
							<%= state %>	
						</option>
					<% end %>
				</select>
			</div>

			<div class="form-group row">
				<label for="time" class="col-sm-4 col-form-label">Time</label>
				<div class="col-sm-4">
					<input type="time" class="form-control" id="time" name="event[time]" value="<%= @event.time.strftime("%H:%M") %>"> 
				</div>
			</div>

			<div class="form-group row">
				<div class="col-sm-2">
					<input type="submit" class="btn btn-default" value="Update Event">
				</div>
			</div>	

		</form>
	</div>
</div>

app/views/events/index.html.erb
<% provide(:page_title, 'Dashboard') %>

<div class="nav_row">
	<div class="container">
		<ul class="nav justify-content-end">
			<li class="nav-item">
					<%= link_to "Edit My Profile", edit_user_path( current_user.id ), :class => "nav-link" %>
			</li>
			<li class="nav-item">
				<%= link_to "Logout", session_path(current_user.id), :method => :delete , :class => "nav-link" %>
			</li>
		</ul>
	</div>
</div>

<div class="row">
	<h1 class="display-4"><%= "Welcome, #{current_user.first_name}!" %></h1>
</div>


<div class="row">
 	<p class="h3">Here are some of the events in your state:</p>
</div>
<div class="row">
	<table class="table table-responsive table-bordered">
		<thead>
			<tr>
				<th>Name</th>
				<th>Date</th>
				<th>City</th>
				<th>State</th>
				<th>Time</th>
				<th>Host</th>
				<th>Action/Status</th>
			</tr>
		</thead>
		<tbody>
			<% @events.where(state: current_user.state).each do |event| %>
				<tr>
					<td><%= link_to "#{event.name}", event_path(event) %></td>
					<td><%= event_date(event.date) %></td>
					<td><%= event.city %></td>
					<td><%= event.state%></td>
					<td><%= event_time(event.time) %></td>
					<td><%= event.user.first_name %></td>
					<td>
						<ul class="list-inline">
							<div class="d-sm-inline-flex">
								<% if event.user != current_user  %>
									<li class="list-inline-item">
										<%= link_to_if(current_user.users_events.find_by(event: event).nil?,"Join", users_events_path(:event_id => event.id), :method => :post ) %>
									</li>
								
									<% if current_user.users_events.find_by(event: event)%>
										<li class="list-inline-item active">Joined</li>
										<li class="list-inline-item"><%= link_to "Cancel", current_user.users_events.find_by(event: event) , method: :delete , :data=> { :confirm => "Are you sure?" } %>
										</li>
									<% end %>

								<% else %>
									<li class="list-inline-item"><%= link_to "Edit", edit_event_path(event.id) %></li>
									<li class="list-inline-item"><%= link_to "Delete", event, :method => :delete, :data => { :confirm => "Are you sure about that?" } %></li>
								<% end %>
							</div>
						</ul>	
					</td>
				</tr>
			<% end %>
		</tbody>
	</table>
</div>

<div class="row">
	<p class="h3">Here are some of the events in other states:</p>
</div>

<div class="row">
	<table class="table table-responsive table-bordered">
		<thead>
			<tr>
				<th>Name</th>
				<th>Date</th>
				<th>City</th>
				<th>State</th>
				<th>Time</th>
				<th>Host</th>
				<th>Action</th>
			</tr>
		</thead>
		<tbody>
		<% @events.where.not(state: current_user.state).each do |event| %>
			<tr>
				<td><%= link_to "#{event.name}", event_path(event) %></td>
				<td><%= event_date(event.date) %></td>
				<td><%= event.city  %></td>
				<td><%= event.state %></td>
				<td><%= event_time(event.time) %></td>
				<td><%= event.user.first_name%></td>
				<td>
					<ul class="list-inline">
						<div class="d-sm-inline-flex">
							<% if event.user != current_user %>
								<% if current_user.users_events.find_by(event: event).nil? %>
									<li class="list-inline-item">
										<%= link_to "Join", users_events_path(:event_id => event.id), :method => :post %>
									</li>
								<% else %>
									<li class="list-inline-item active">Joined</li>
									<li class="list-inline-item">
										<%= link_to "Cancel", current_user.users_events.find_by(event: event), :method => :delete , :data => { :confirm => "Are you sure?" } %>
									</li>
								<% end %>
							<% else %>
								<li class="list-inline-item">
									<%= link_to "Edit", edit_event_path(event.id)%>
								</li>
								<li class="list-inline-item">
									<%= link_to "Delete", event, :method => :delete , :data => { :confirm => "Are you sure about that?" } %>
								</li>
							<% end %>
						</div>
					</ul>
				</td>
			</tr>
		<% end %>
		</tbody>
	</table>
</div>
<div class="row">
	<div class="col-md-6">
		<div class="form-header">
			<p class="h4">Add Event</p>
		</div>

		<form action="/events" method="post">
			<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
			<div class="form-group row">
				<label for="name" class="col-sm-4 col-form-label">Event Name</label>
				<div class="col-sm-7">
					<input type="text" class="form-control" id="name" name="event[name]">
				</div>
			</div>

			<div class="form-group row">
				<label for="date" class="col-sm-4 col-form-label">Date</label>
				<div class="col-sm-5">
					<input type="date" class="form-control" id="date" name="event[date]">
				</div>
			</div>

			<div class="form-group row">
				<label for="location" class="col-sm-4 col-form-label">Location</label>
				<div class="col-sm-5">
					<input type="text" id="city" name="event[city]" class="form-control">
				</div>
				<select name="event[state]" id="state" class="form-control col-sm-2">
					<% states.each  do |key, state| %>
						<option value="<%= state %>" id="state">
							<%= state %>
						</option>
					<% end %>
				</select>
			</div>

			<div class="form-group row">
				<label for="time" class="col-sm-4 col-form-label">Time</label>
				<div class="col-sm-5">
					<input type="time" class="form-control" id="time" name="event[time]">
				</div>
			</div>

			<div class="form-group row">
				<div class="col-sm-2">
					<input type="submit" class="btn btn-default" value="Add Event">
				</div>
			</div>
			
		</form>
	</div>
</div>

app/views/events/show.html.erb
<% provide(:page_title, 'Event Detail') %>
<%= render partial: "shared/navbar_edit", locals: { user: current_user } %>

<div class="row">
	<h1 class="display-4"><%= @event.name%></h1>
</div>

<div class="row">
	<div class="col-sm-8 col-md-7 col-lg-7">
		<dl class="row">
			<dt class="col-sm-4">Host:</dt>
			<dd class="col-sm-5 pull-sm-2"><%= @event.user.first_name %></dd>
			
			<dt class="col-sm-4">Date:</dt>		
			<dd class="col-sm-5 pull-sm-2"><%= event_date(@event.date)%></dd>	
			
			<dt class="col-sm-4">Location:</dt>
			<dd class="col-sm-5 pull-sm-1"><%= "#{@event.city}, #{@event.state}" %></dd>

			<dt class="col-sm-4">Attendees:</dt>
			<dd class="col-sm-5"><%= @event.users_events.count %></dd>
		</dl>
	</div>
	<div class="col-sm-8 col-md-7 col-lg-7">
		<table class="table table-bordered">
		<thead>
			<tr>
				<th>Name</th>
				<th>Location</th>
				<th>State</th>
			</tr>
		</thead>
		<tbody>
			<% @event.users_events.each do |user_event| %>
			<tr>
				<td><%= "#{user_event.user.first_name} #{user_event.user.last_name}" %></td>
				<td><%= user_event.user.city %></td>
				<td><%= user_event.user.state %></td>
			</tr>
			<% end %>
		</tbody>
		</table>
	</div>

	<div class="col-sm-4 col-md-5 offset-md-2 col-lg-5 offset-lg-0">
		<h6>Event Discussion</h6>
		<div class="card card-outline-info mb-3">
  		<div class="card-block">
  		<% @comments.each do |comment| %>
    		<p class="text-left"><strong><%= "#{comment.user.first_name} #{comment.user.last_name}: "%></strong><%= comment.message %></p>
    	<% end %>
  		</div>

		</div>
		<h6>Add Comment:</h6>
    	<form action="/comments" method="post">
    		<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
    		<input type="hidden" name="comment[event_id]" value="<%= @event.id %>">
    		<input type="hidden" name="comment[user_id]" value="<%= current_user.id %>">
    		<textarea name="comment[message]" id="message" cols="32" rows="4" class="card card-outline-info mb-3"></textarea>
    		<input type="submit" class="btn btn-secondary" value="Submit Comment">
   		</form>
	</div>
</div>



	

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:page_title) %> | Events</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

	<body>
		<div class="container <%= controller_name %> <%= action_name %>">
			<div class="row justify-content-center">
				<div class="col-md-5 col-md-offset-4">
					<%= render 'shared/messages' %>
				</div>
			</div>
		 	<%= yield %>
		</div>
	</body>
</html>

app/views/shared/_messages.html.erb
<div class="flash_wrapper">
	<% flash.each do |key, msg| %>
		<div class="alert alert-<%=key %>">
			<span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
			<ul>
				<li>
					<%= msg %>
				</li>
			</ul>
		</div>
	<% end %>
</div>

app/views/shared/_navbar_edit.html.erb
<div class="nav_row">
	<div class="container">
		<ul class="nav justify-content-end">
			<li class="nav-item">
				<%= link_to "Events Dashboard", events_path, :class => "nav-link" %>
			</li>
			<li class="nav-item">
				<%=  link_to "Logout", session_path(current_user), method: :delete, :class => "nav-link" %>
			</li>
		</ul>
	</div>
</div>

app/views/users/edit.html.erb
<% provide(:page_title, 'Edit Your Profile') %>
<%= render partial: "shared/navbar_edit", locals: { user: current_user } %>
<div class="row">
	<div class="edit_head">
		<h5>Edit Your Profile</h5>
	</div>
</div>
<div class="row justify-content-center">
	<div class="col-md-8">
		<form action="/users" method="post">
			<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
			<input type="hidden" name="_method" value="patch">

			<div class="form-group row">
				<label for="first_name" class="col-sm-4 col-form-label">First Name</label>
				<div class="col-sm-6">
					<input type="text" id="first_name" name="user[first_name]" value="<%= @user.first_name %>" class="form-control">
				</div>
			</div>

			<div class="form-group row">
				<label for="last_name" class="col-sm-4 col-form-label">Last Name</label>
				<div class="col-sm-6">
					<input type="text" id="last_name" name="user[last_name]" value="<%= @user.last_name%>" class="form-control">
				</div>
			</div>

			<div class="form-group row">
				<label for="email" class="col-sm-4 col-form-label">Email</label>
				<div class="col-sm-6">
					<input type="text" id="email" name="user[email]" value="<%= @user.email %>" class="form-control">
				</div>
			</div>

			<div class="form-group row">
				<label for="location" class="col-sm-4 col-form-label">Location</label>
				<div class="col-sm-4">
					<input type="text" id="city" name="user[city]" class="form-control" value="<%= @user.city %>">
				</div>
				<select name="user[state]" id="state" class="form-control col-sm-2">
					<% states.each do |key, state| %>
						<option value="<%= state %>" id="state" <% if state == @user.state %> selected="selected" <% end %> >
							<%= state %>	
						</option>
					<% end %>
				</select>
			</div>

			<div class="form-group row">
				<div class="col-sm-2 offset-sm-10">
					<input type="submit" class="btn btn-default" value="Update">
				</div>
			</div>
		</form>
	</div>
</div>